export const USER_API_ENDPOINT= "https://quiz-project-backend-zf3w.onrender.com/api/v1/user"
export const COURSE_API_ENDPOINT= "https://quiz-project-backend-zf3w.onrender.com/api/v1/course"
export const ENROLLMENT_API_ENDPOINT= "https://quiz-project-backend-zf3w.onrender.com/api/v1/enrollment"
export const QUESTIONS_API_ENDPOINT= "https://quiz-project-backend-zf3w.onrender.com/api/v1/question"
export const WEEK_API_ENDPOINT= "https://quiz-project-backend-zf3w.onrender.com/api/v1/week"